### ISSUE TITLE
Validation error on unique_together fields outputs empty message.

### ISSUE THREAD

**Issue by geekashu** [tOgg1/graphene-django-cud#30] opened 2020-08-30 17:49 UTC
```
class Dashboard(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dashboards')

    class Meta:
        ordering = ['-id']
        unique_together = ['name', 'owner']
```

The validation error gets hit properly, but the message field is empty for this error.
`{"errors":[{"message":"","locations":[{"line":2,"column":21}],"path":["createDashboard"]}],"data":{"createDashboard":null}}`

**Comment by tOgg1** [comment] 2020-09-08 06:15
It's not clear to me that this is related to this library, but I'll do a quick investigation.

**Comment by tOgg1** [comment] 2021-01-02 09:29
I am unable to reproduce this.

**Comment by tOgg1** [comment] 2022-03-13 10:13
Closing until further information is provided.

**Closed by tOgg1** 2022-03-13 10:13 UTC
Labels: needs verification
