### ISSUE TITLE
Choices field not marked optional in DjangoPatchMutation

### ISSUE THREAD

**Issue by martasd** [tOgg1/graphene-django-cud#5] opened 2019-12-04 10:23 UTC
I have the following model and mutation:

```
class Report(BaseModel):
    workspace = ForeignKey(Workspace, on_delete=CASCADE)
    name = CharField(max_length=255)

    MODULES = (("EVENT", "Event"), ("TASK", "Task"), ("AGENDA", "Agenda"), ("BEO", "Beo"))
    module = CharField(max_length=32, choices=MODULES)
    author = ForeignKey(UserProfile, on_delete=CASCADE)
    config = JSONField()
```

```
class UpdateReport(DjangoPatchMutation):
    class Meta:
        model = Report
        type_name = "UpdateReportInput"


```

`module` is NOT optional even though every field should be optional by default in `DjangoPatchMutation` according to the documentation:

![image](https://user-images.githubusercontent.com/591911/70134155-c7667c80-1687-11ea-84af-bc8dbdd70e6e.png)

**Comment by tOgg1** [comment] 2019-12-04 10:26
Thanks for the report.

This is a bug I am aware of and is caused by a bad caching of the generated enum-types.

I will fast-track the fix of this.

**Comment by martasd** [comment] 2019-12-04 10:30
Excellent!

**Comment by tOgg1** [comment] 2019-12-10 10:49
This should be fixed in 0.2.1.

**Closed** 2020-01-04 06:25 UTC
